title: 'IStorage'
author: Ilya Suchkov
email: 'suchkow@proton.me'
description: 'The website of Ilya Suchkov.'
github: suchkow
timezone: Europe/Moscow
url: https://suchkow.github.io/
language: en_US

# social images

favicon: /static/logos/logo.svg
twitter: "@good-luck-twitter-existing-in-a-few-years"
social-media-image-url: /static/logos/logo.svg
twitter-card-image: do.jpg
iOS-icon: /static/logos/logo.svg


highlighter: rouge
markdown: kramdown
parse_block_html: false
show_drafts: true
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      blogpost: true
      layout: post
      og-type: article
      social-media-image: false
    
  -    
    scope:
      path: ""
      type: "pages"
    values:
      layout: page 
      social-media-image: false   

  -    
    scope:
      path: ""
      type: "no-index"
    values:
      layout: page
      no-index: true
      social-media-image: false

collections:
  pages:
    output: true
  no-index:
    output: true
  unlisted:
    output: true
  authors:

plugins:
  - jekyll-feed

feed:
  posts_limit: 25
  categories:
    - articles
    - notes
    - now