title: "🌀istorage"
author: "Ilya Suchkov"
description: ""
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout
show_excerpts: true        # show article excerpts on the home page
show_frame: true          # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu
navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "about.md"}
  - {file: "storage.md"}
  - {file: "archive.html"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: suchkow@proton.me, url: "mailto:suchkow@proton.me"}
  - {title: github.com/suchkow, url: "https://github.com/suchkow/"}
  - {title: RSS, url: "/feed.xml"}
  # - {title: Subscribe, icon: rss, url: "/feed.xml"}
  # - {title: Github, icon: github, url: "https://github.com/niklasbuschmann/contrast"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
